version: 2
jobs:
  deploy:
    working_directory: ~/player_sdk_android
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS
      - run:
         name: Config Licenses
         command: |
            curl -fL https://getcli.jfrog.io | sh
            chmod +x jfrog
            cp -R assets/licenses $ANDROID_HOME/
      - run:
         name: Generate Release
         command: cd sambaplayersdk && ../gradlew assembleRelease --stacktrace
      - run:
         name: Deploy Player to BINTRAY
         command: |
            if [ "${CIRCLE_BRANCH}" == "ft-circle_ci_2" ]; then
              assets/publish.sh $BINTRAY_USER $BINTRAY_API_KEY dev
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              assets/publish.sh $BINTRAY_USER $BINTRAY_API_KEY
            fi
      - store_artifacts:
          path: /tmp/circleci-artifacts

workflows:
  version: 2
  player-sdk-android:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - ft-circle_ci_2
                - master
